\input texinfo    @c -*- mode: texinfo; coding: utf-8; -*-
@comment %**start of header
@documentencoding UTF-8

@c EN
@documentlanguage en
@setfilename gauche-makiki.en.info
@settitle Makiki - Simple HTTP server in Gauche
@dircategory The Algorithmic Language Scheme
@direntry
* Gauche Makiki: (gauche-makiki.en.info).	Simple HTTP Server in Gauche
@end direntry
@c JP
@documentlanguage ja
@setfilename gauche-makiki.ja.info
@settitle Makiki - GaucheによるシンプルなHTTPサーバ
@dircategory The Algorithmic Language Scheme
@direntry
* Gauche Makiki: (gauche-makiki.ja.info).	Gaucheによる簡単なHTTPサーバ
@end direntry
@c COMMON
@comment %**end of header

@titlepage
@title Makiki - Simple HTTP server in Gauche
@subtitle version @VERSION@
@author Shiro Kawai (shiro@@acm.org)

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2023  Shiro Kawai  <shiro@@acm.org>

@end titlepage

@node Top, Introduction, (dir), (dir)

@ifnottex
This is a reference manual of Gauche-makiki,
an HTTP server written in Gauche Scheme implementation.
This manual is for version @VERSION@.
@end ifnottex

@menu
* Introduction::
* Getting started::
* API reference::
* Index::
@end menu

@node Introduction, Getting started, Top, Top
@chapter Introduction

Gauche-makiki is a simple multithreaded http server intended for
embedded http server capability, or
write an application server in Gauche.

The basic functionalities are available by just one file,
@code{makiki.scm}, so you can just copy that file into
your source tree, if you want a simple embedded http server in
your application.

This package also has several auxiliary modules, and you want to take
the standard installation procedure if you want to write an
application server.

Gauche-makiki is not particularly written for speed or bandwidth.
You can put Makiki server behind a reverse proxy, and let it serve
only dynamic parts of the web application, while let the front-end
webserver (e.g. Apache) serve the static content.

@menu
* Installation::
@end menu

@node Installation,  , Introduction, Introduction
@section Installation

@subheading Prerequisites

You need Gauche 0.9.14 or later:
@url{https://practical-scheme.net/Gauche}.

In order to serve https, Gauche needs to be configured with TLS support.
You can check it with @code{gosh -V}, and look for @code{gauche.net.tls}
line.  If it lists a subsystem (e.g. @code{(gauche.net.tls mbedtls)}),
TLS is supported.
If it is empty (e.g. @code{(gauche.net.tls)}, TLS support is not
available.

@subheading Installation

You can install Gauche-makiki from git source tree:

@example
git clone https://github.com/shirok/Gauche-makiki.git
cd Gauche-makiki
./configure
make check
make install
@end example

The @code{configure} script (it is @emph{not} generated from @code{autoconf})
checks if you have Gauche installed in @code{PATH}, and tries to
set up installation destination in the same location.  If you want
to install Gauche-makiki in a different location, give it with
@code{--prefix} option.

@example
./configure --prefix=/path/to/install/location
@end example

@node Getting started, API reference, Introduction, Top
@chapter Getting started





@node API reference, Index, Getting started, Top
@chapter API reference


@node Index,  , API reference, Top
@chapter Index

@printindex fn

@contents
@bye

@c Local variables:
@c outline-regexp: "@chap\\|@unnu\\|@\\(sub\\)*section"
@c end:
